services:
  - type: web
    name: django-sales-distribution
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn sales_distribution.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: DJANGO_SETTINGS_MODULE
        value: sales_distribution.settings.production
      - key: DATABASE_URL
        sync: false
